version: '3.8'

# Servizi - è un elenco dei componenti dell'applicazione
services: 

# Nginx Service
 nginx:
  image: nginx:1.19-alpine # indica l'immagine da utilizzare
  ports: 
   - 80:80 #indica che vogliamo mappare la porta 80 sulla macchina locale, verremo inoltrati alla porta 80 del contenitore Nginx
  volumes:
   - ./src/backend:/var/www/backend
   - ./.docker/nginx/conf.d:/etc/nginx/conf.d
   - phpmyadmindata:/var/www/phpmyadmin
  depends_on:
   - backend
   - phpmyadmin
   - frontend
# Servizio Backend
 backend:
  build: ./src/backend
  working_dir: /var/www/backend
  volumes:
   - ./src/backend:/var/www/backend
  depends_on:
   mysql: # dichiariamo che il servizio mysql deve esser avviato prima di backend
    condition: service_healthy # ci permette di specificare a quale condizione il container è pronto. In questo caso non solo vogliamo avviare il contenitoe ma anche crare il database prima che il container backend tenti di accedervi, causando eventuali errori

#Servizio Frontend
 frontend:
  build: ./src/frontend
  working_dir: /var/www/frontend
  volumes:
  - ./src/frontend:/var/www/frontend
  depends_on:
   - backend

# MySQL Service
 mysql:
  image: mysql:8 # immagine ufficiale versione 8
  environment: # contiene delle variabili d'ambiente che al momento della creazione del container verranno impostate su di esso
   MYSQL_ROOT_PASSWORD: root # password del db demo
   MYSQL_DATABASE: demo # nome database
  volumes: # montiamo le directory collegate
  - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf # questo sarà usato per impostare il set di caratteri in utf8mb4_unicode_ci impostazione predefinita
  - mysqldata:/var/lib/mysql
  healthcheck:
   test: mysqladmin ping -h 127.0.01 -u root --password=$$MYSQL_ROOT_PASSWORD
   interval: 5s # poichè il controllo di integrità impostato con il condition, potrebbe non funzionare al primo avvio, abbiamo impostato un test che si ripeterà ogni 5 secondi per 10 volte
   retries: 10 #
# PhpMyAdmin Service
 phpmyadmin:
  image: phpmyadmin/phpmyadmin:5-fpm-alpine
  environment:
   PMA_HOST: mysql
  volumes:
   - phpmyadmindata:/var/www/html
  depends_on:
   mysql:
    condition: service_healthy

# Volumes
volumes:

 mysqldata: # senza questo volume, ogni qualvolta il contenitore mysql viene distrutto il database verrebbe distrutto con esso. Per renderlo persistente usiamo questo volume che memorizza i dati in locale

 phpmyadmindata:













